"""Fix bug

Revision ID: 3e187c767505
Revises: edb078e10dac
Create Date: 2022-09-17 17:23:07.591793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e187c767505'
down_revision = 'edb078e10dac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('address', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'address')
    op.drop_column('contacts', 'email')
    # ### end Alembic commands ###
